# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0015_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supdem.MyUser'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supdem.MyUser'),
        ),
        migrations.AlterField(
            model_name='item',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supdem.MyUser'),
        ),
        migrations.AlterField(
            model_name='resetpasswordkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supdem.MyUser'),
        ),
    ]
