# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0016_auto_20170527_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name',
        ),
    ]
