# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0017_auto_20170603_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='centre',
        ),
    ]
