# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0018_remove_item_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='poster',
        ),
    ]
