# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0019_auto_20170609_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_offer',
        ),
    ]
