# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0020_remove_item_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Owner',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
