# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0021_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
