# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0023_auto_20170621_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
