# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0025_auto_20170623_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expirydate',
            field=models.DateTimeField(default="2018-01-01"),
            preserve_default=False,
        ),
    ]
