# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0028_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='last_change',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='reactor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_poster',
        ),
        migrations.RemoveField(
            model_name='message',
            name='languagecode',
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
