# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0029_auto_20170715_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dialogue',
        ),
        migrations.AddField(
            model_name='message',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='supdem.Item'),
            preserve_default=False,
        ),
    ]
