# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0031_remove_item_active_dialogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryquestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryquestionoption',
            name='categoryquestion',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='item',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='item',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='CategoryQuestion',
        ),
        migrations.DeleteModel(
            name='CategoryQuestionOption',
        ),
        migrations.DeleteModel(
            name='Dialogue',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
