# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0033_auto_20171013_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centre',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
