# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supdem', '0034_auto_20171022_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expirydate',
        ),
    ]
